add_passcode:
  fields:
    lock_mac:
      required: true
      selector:
        text:
    passcode:
      required: true
      selector:
        text:
    passcode_type:
      default: "period"
      selector:
        select:
          options:
            - "period"
            - "permanent"
    start_date:
      default: "0001311400"
      selector:
        text:
    end_date:
      default: "9912311400"
      selector:
        text:

add_fingerprint:
  fields:
    lock_mac:
      required: true
      selector:
        text:
    start_date:
      default: "200001010000"
      selector:
        text:
    end_date:
      default: "209912312359"
      selector:
        text:
    scan_timeout:
      default: 45
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: s

list_fingerprints:
  fields:
    lock_mac:
      required: true
      selector:
        text:

update_fingerprint:
  fields:
    lock_mac:
      required: true
      selector:
        text:
    fingerprint_number:
      required: true
      selector:
        text:
    start_date:
      default: "200001010000"
      selector:
        text:
    end_date:
      default: "209912312359"
      selector:
        text:

delete_fingerprint:
  fields:
    lock_mac:
      required: true
      selector:
        text:
    fingerprint_number:
      required: true
      selector:
        text:

delete_passcode:
  fields:
    lock_mac:
      required: true
      selector:
        text:
    passcode:
      required: true
      selector:
        text:
    passcode_type:
      default: "period"
      selector:
        select:
          options:
            - "period"
            - "permanent"

clear_passcodes:
  fields:
    lock_mac:
      required: true
      selector:
        text:

clear_fingerprints:
  fields:
    lock_mac:
      required: true
      selector:
        text:
